{% set name = "openlineage-integration-common" %}
{% set version = "1.30.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6cc8c37a2b3e59f047070dcb426f200f9707885727719f318ce832d67c6ef547

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - attrs >=19.3.0
    - openlineage-python ==1.30.0
    - openlineage-sql ==1.30.0
    # - types-python-dateutil 
    # - types-PyYAML 
    # - sqlalchemy <2.0.0,>=1.3.24
    # - pyyaml >=5.3.1
    # - python-dateutil 
    # - pytest-mock 
    # - pytest-cov 
    # - pytest 
    # - pandas 
    # - mypy >=0.960
    # - mock 
    # - jinja2 
    # - great-expectations <0.15.35,>=0.13.26
    # - google-crc32c >=1.1.2
    # - google-cloud-core >=1.6.0
    # - google-cloud-bigquery <4.0.0,>=2.15.0
    # - google-auth >=1.30.0
    # - google-api-core >=1.26.3
    # - dbt-core >=0.20.0
    # - boto3 >=1.15.0
    # - types-python-dateutil 
    # - types-PyYAML 
    # - sqlalchemy <2.0.0,>=1.3.24
    # - pyyaml >=5.3.1
    # - python-dateutil 
    # - pytest-mock 
    # - pytest-cov 
    # - pytest 
    # - pandas 
    # - mypy >=0.960
    # - mock 
    # - jinja2 
    # - great-expectations <0.15.35,>=0.13.26
    # - google-crc32c >=1.1.2
    # - google-cloud-core >=1.6.0
    # - google-cloud-bigquery <4.0.0,>=2.15.0
    # - google-auth >=1.30.0
    # - google-api-core >=1.26.3
    # - dbt-core >=0.20.0
    # - boto3 >=1.15.0

test:
  imports:
    - openlineage.common
    - openlineage.common.provider
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: OpenLineage common python library for integrations
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
