{% set name = "openlineage-integration-common" %}
{% set version = "1.34.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 00ebcb1de887cc6ac6841183ca4dc0ec8ba845da80a6d34dc618cbb93c40cef6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - attrs >=19.3.0
    - openlineage-python =={{ version }}
    - openlineage-sql =={{ version }}

test:
  imports:
    - openlineage.common
    - openlineage.common.provider
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: OpenLineage common python library for integrations
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
