{% set name = "openlineage-integration-common" %}
{% set version = "1.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb811d109fba67fae89902bd35c2a98b3c8ba2eb20874ef2513b85520809e24d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - attrs >=19.3.0
    - openlineage-python =={{ version }}
    - openlineage-sql =={{ version }}

test:
  imports:
    - openlineage.common
    - openlineage.common.provider
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenLineage common python library for integrations
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
