# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: openlineage-integration-common
  version: "1.36.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/openlineage_integration_common-${{ version }}.tar.gz
  sha256: 753dc34dff6a4ef60e2525452f52567952c1d21c63b96195acb192d0ba320463

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - attrs >=19.3.0
    - openlineage-python ==${{ version }}
    - openlineage-sql ==${{ version }}
    - pyyaml >=5.3.1

tests:
  - python:
      imports:
        - openlineage.common
        - openlineage.common.provider
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: OpenLineage common python library for integrations
  homepage: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
